// apps/client-solid/src/components/ui/preview.tsx
import { splitProps, type Component, type ComponentProps } from "solid-js";
import { cn } from "~/lib/utils";

export const Preview: Component<ComponentProps<"div">> = (props) => {
  const [local, others] = splitProps(props, ["class"]);

  return (
    <div
      class={cn("not-prose p-5 border-2 shadow-neo-xl bg-white", local.class)}
      {...others}
    ></div>
  );
};

// apps/client-react/components/ui/preview.tsx
import { cn } from "@/lib/utils";
import React from "react";

export function Preview({
  className,
  ...props
}: React.ComponentPropsWithRef<"div">) {
  return (
    <div
      className={cn(
        "not-prose bg-white shadow-neo-xl mx-auto p-5 border",
        className
      )}
      {...props}
    />
  );
}
