// apps/client-vue/components/ui/preview.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";

const props = defineProps<{ class?: HTMLAttributes["class"] }>();
</script>

<template>
  <div
    :class="
      cn('not-prose bg-white shadow-neo-xl mx-auto p-5 border', props.class)
    "
  >
    <slot></slot>
  </div>
</template>

// apps/client-react/components/ui/preview.tsx
import { cn } from "@/lib/utils";
import React from "react";

export function Preview({
  className,
  ...props
}: React.ComponentPropsWithRef<"div">) {
  return (
    <div
      className={cn(
        "not-prose bg-white shadow-neo-xl mx-auto p-5 border",
        className
      )}
      {...props}
    />
  );
}
