// apps/client-solid/src/components/ui/progress.tsx
import {
  createMemo,
  mergeProps,
  splitProps,
  type Component,
  type ComponentProps,
} from "solid-js";
import { cn } from "~/lib/utils";

export const Progress: Component<
  Exclude<ComponentProps<"div">, "children"> & {
    min?: number;
    value?: number;
    max?: number;
  }
> = (props) => {
  const mergedProps = mergeProps({ min: 0, max: 100, value: 0 }, props);
  const [local, others] = splitProps(mergedProps, [
    "class",
    "min",
    "max",
    "value",
  ]);

  const percentage = createMemo(() => {
    return local.max === 0
      ? 0
      : (1 - (local.value - local.min) / (local.max - local.min)) * 100;
  });

  return (
    <div
      class={cn(
        "border-2 flex items-center justify-center overflow-hidden h-4 relative",
        local.class
      )}
      aria-valuemin={local.min}
      aria-valuemax={local.max}
      aria-valuenow={local.value}
      {...others}
    >
      <div
        class="absolute w-full h-full bg-amber-400 transition-all"
        style={{ transform: `translateX(-${percentage()}%)` }}
      ></div>
    </div>
  );
};

// apps/client-react/components/ui/progress.tsx
import { cn } from "@/lib/utils";
import React, { useMemo } from "react";

type Props = {
  min?: number;
  max?: number;
  value?: number;
} & React.ComponentPropsWithRef<"div">;

export function Progress({
  min = 0,
  max = 100,
  value = 0,
  className,
  ...props
}: Props) {
  const percentage = useMemo(
    () => (max === 0 ? 0 : (1 - (value - min) / (max - min)) * 100),
    [min, max, value]
  );

  return (
    <div
      role="progressbar"
      aria-valuemin={min}
      aria-valuemax={max}
      aria-valuenow={value}
      className={cn(
        "border-2 flex items-center justify-center overflow-hidden h-4 relative",
        className
      )}
      {...props}
    >
      <div
        className="absolute w-full h-full bg-amber-400 transition-all"
        style={{ transform: `translateX(-${percentage}%)` }}
      ></div>
    </div>
  );
}
