// apps/client-react/components/ui/button.tsx
import { cn } from "@/lib/utils";
import React from "react";

export function Button({
  className,
  ...props
}: React.ComponentPropsWithRef<"button">) {
  return (
    <button
      {...props}
      className={cn(
        "h-10 flex items-center justify-center font-head cursor-pointer px-4 border-2 shadow-neo-md disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-neo-md active:shadow-neo-sm transition",
        className
      )}
    />
  );
}

// apps/client-vue/components/ui/button.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";

const props = defineProps<{ class?: HTMLAttributes["class"] }>();
</script>

<template>
  <button
    :class="
      cn(
        'h-10 flex items-center justify-center font-head cursor-pointer px-4 border-2 shadow-neo-md disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-neo-md active:shadow-neo-sm transition',
        props.class
      )
    "
  >
    <slot></slot>
  </button>
</template>
