// apps/client-svelte/src/lib/components/ui/preview.svelte
<script lang="ts">
	import type { SvelteHTMLElements } from 'svelte/elements';

	type Props = SvelteHTMLElements['div'];

	const { class: className, children, ...props }: Props = $props();
</script>

<div class="not-prose bg-white shadow-neo-xl mx-auto p-5 border {className}" {...props}>
	{@render children?.()}
</div>

// apps/client-vue/components/ui/preview.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";

const props = defineProps<{ class?: HTMLAttributes["class"] }>();
</script>

<template>
  <div
    :class="
      cn('not-prose bg-white shadow-neo-xl mx-auto p-5 border', props.class)
    "
  >
    <slot></slot>
  </div>
</template>
