// apps/client-svelte/src/routes/(page)/timer/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button.svelte';
	import Preview from '$lib/components/ui/preview.svelte';
	import Progress from '$lib/components/ui/progress.svelte';
	import Slider from '$lib/components/ui/slider.svelte';

	let elapsed = $state(0);
	let duration = $state(0);
	let interval: ReturnType<typeof setInterval>;

	function start() {
		interval = setInterval(() => {
			elapsed += 0.1;
			if (elapsed >= duration) {
				elapsed = duration;
				clearInterval(interval);
			}
		}, 100);
	}

	function reset() {
		elapsed = 0;
		clearInterval(interval);
		start();
	}

	$effect(() => {
		if (!duration) return;
		start();
		return () => clearInterval(interval);
	});
</script>

<h1 class="font-head">Timer</h1>

<Preview class="flex flex-col gap-5">
	<div class="font-head text-center text-2xl">{elapsed.toFixed(1)} / {duration.toFixed(1)}</div>
	<label class="flex items-center gap-2">
		<span>Elapsed Time:</span>
		<Progress class="grow" value={elapsed} max={duration} />
	</label>

	<label class="flex items-center gap-2">
		<span>Duration:</span>
		<Slider class="w-full" bind:value={duration} step={0.1} min={0} max={20} />
	</label>

	<Button onclick={reset}>Reset</Button>
</Preview>

<p>
	Fourth task of <a
		target="_blank"
		rel="noopener noreferrer"
		href="https://eugenkiss.github.io/7guis/tasks/#timer"
		>The 7 Tasks from 7GUIs
	</a>.
</p>

// apps/client-solid/src/routes/(page)/timer.tsx
import { createSignal, JSX } from "solid-js";
import { Button } from "~/components/ui/button";
import { Preview } from "~/components/ui/preview";
import { Progress } from "~/components/ui/progress";
import { Slider } from "~/components/ui/slider";

export default function Page() {
  let interval: ReturnType<typeof setInterval>;
  const [elapsed, setElapsed] = createSignal(0);
  const [duration, setDuration] = createSignal(0);

  function start() {
    interval = setInterval(() => {
      let newElapsed = elapsed() + 0.1;
      if (newElapsed >= duration()) {
        newElapsed = duration();
        clearInterval(interval);
      }
      setElapsed(newElapsed);
    }, 100);
  }

  function reset() {
    setElapsed(0);
    clearInterval(interval);
    start();
  }

  const handleDurationChange: JSX.EventHandler<HTMLInputElement, InputEvent> = (
    e
  ) => {
    const value = e.currentTarget.valueAsNumber;
    setDuration(value);
    clearInterval(interval);
    start();
  };

  return (
    <>
      <h1>Timer</h1>
      <Preview class="space-y-5">
        <p class="text-2xl text-center font-head">
          {elapsed().toFixed(1)} / {duration().toFixed(1)}
        </p>

        <label class="flex items-center gap-2">
          <span>Elapsed Time:</span>
          <Progress class="grow" value={elapsed()} max={duration()} />
        </label>
        <label class="flex items-center gap-2">
          <span>Duration:</span>
          <Slider
            class="grow"
            value={duration()}
            min={0}
            max={20}
            oninput={handleDurationChange}
          />
        </label>

        <Button class="w-full" onclick={reset}>
          Reset
        </Button>
      </Preview>

      <p>
        Fourth task of{" "}
        <a
          target="_blank"
          rel="noopener noreferrer"
          href="https://eugenkiss.github.io/7guis/tasks/#timer"
        >
          The 7 Tasks from 7GUIs
        </a>
        .
      </p>
    </>
  );
}
